from typing import Dict


def count_nucleotides(dna: str = "") -> Dict[str, int]:
    nt_counts: Dict[str, int] = {"A": 0, "C": 0, "G": 0, "T": 0}

    for nt in dna:
        nt_upper = nt.upper()
        if nt_upper in nt_counts:
            nt_counts[nt_upper] += 1

    return nt_counts


def format_nucleotide_counts(nt_counts: Dict[str, int]) -> str:
    return " ".join(str(nt_counts[nt]) for nt in "ACGT")


nt_counts = count_nucleotides(
    "GAGAGTTCTGCAATAAGCTGCGACGACTTCGGTCGGCGGTTCACAACGTTGGTAACCGCATTGTCGCTACCACTTACAACATGAGTCACGTGCACTCTTCAGAATCCCAAATTCTCGTCCCATCGTGCTTCGTCTTCATAAAGCCCATAGACTATTAGGAATGAACAAGACCTCTGTGGGTCACAGGGTCGGGGGAGCAGAGTGGTCTGACTGCCCCGACCGTAGTGTAGGGCCCCCAATCTTTATAAATAATTGACCGCAAACCAGTCGACGGCGAGTTGCGAGGCAATGAGCGTAAGTAGACAAACTAATTGCAAGTGGGGTGTTTCCCGATTCGGATTTATGAGGGGCAAGGAAAGAGGTGAGTGCAGAGCACCACCGCGGTCTGACACCCAGCTCTATGCGTGTCTTTCTTCGCAATCCAACGTGTCTTGGATGCTGGATCGGATTCCACGAGCCGGCCCGACAACCTAGTCGCGTGCCATTACGAACCATCTGCTAAAGTCTTATCGTCTTGGTTATAAGTCAGGGGCTGCCGGTACTTGACAATAAGTGACACACGTACGTCGCGTAAATTAGAGCACGCCTATCTCGCTAAACTTAATTGTATCCTTCTTCGGTTTAGAAAAGTATGTGCACCTGCCGGTAGAATGTCGGCTACTAAAAAGTCAAGAAATCTGTCCGGTTACGTTAGAGGCAAGCACACGGATAATTCGCGGGAAACCATCCGGAGCGGTCGAAGGGAACTCTCCCTACACACGACCCTAACACCTTAATGTTCAAGGAGTCTAATGGTTTGAGTGGCATGATTCATGCTGTCCCAGCTAGAAATCCCACAGATGGGTATTTGCAGATGAGGAAGAAGGTGCAATTAAGCTCATAAGGTCCATTGCATCTGCCTCCGCTCTCAGGGCGTAGAAAGCTTCATCGTCGCGTAGTCGTTCCGCGAGCATCGGCATGACTACTTCATCGGTCAGTTTGGTTAG"
)

print(format_nucleotide_counts(nt_counts))
